services:
  - docker

jobs:
  include:
    - stage: Static backend code analysis
      script: docker build -f backend/Dockerfile-static-backend-analysis backend/
    - stage: Backend + PostgreSQL test
      env:
        - DOCKER_COMPOSE_VERSION=1.29.1
      script: docker-compose -f docker-compose-backend-test.yml up --exit-code-from web
    - stage: Static frontend code analysis
      script: docker build -f frontendapp/Dockerfile-static-frontend-analysis frontendapp/
