services:
  - docker

jobs:
  include:
    - stage: test
      name: Static backend code analysis
      script: docker build -f backend/Dockerfile-static-backend-analysis backend/
    - stage: test
      name: Backend + PostgreSQL test
      env:
        - DOCKER_COMPOSE_VERSION=1.29.1
      script: docker-compose -f docker-compose-backend-test.yml up --exit-code-from web
    - stage: test
      name: Static frontend code analysis
      script: docker build -f frontendapp/Dockerfile-static-frontend-analysis frontendapp/
    - stage: test
      name: Frontend test
      script: docker build -f frontendapp/Dockerfile-frontend-test frontendapp/
    - stage: deploy
      if: branch = main
      name: backend deploy to heroku
      language: generic
      deploy:
        - provider: heroku
          api_key: $HEROKU_API_KEY
          app: fitkeeper-backend
          on: main
    - stage: deploy
      if: branch = main
      name: frontend deploy to netlify
      language: node_js
      node_js: 10.19.0
      script:
        - npm install netlify-cli -g
        - cd frontendapp && npm install && ng build --prod && cd -
      deploy:
        - provider: script
          script: netlify deploy --prod
          skip_cleanup: true
          on: main
