FROM node:10.19.0
ARG NETLIFY_AUTH_TOKEN
ARG NETLIFY_SITE_ID
WORKDIR /app
COPY . /app/
RUN npm install netlify-cli
RUN cd frontendapp && npm install && npm run build:prod --prod && cd -
RUN ./node_modules/.bin/netlify deploy --prod
