[build]
  base = "frontendapp/"
  command = "ng build --prod"
  functions = "netlify/functions"
  publish = "dist/frontendapp"
[context.production]
  base = "frontendapp/"
  command = "ng build --prod"
  functions = "netlify/functions"
  publish = "dist/frontendapp"
