FROM kubamacek/fitkeeper:backendimage1.0
ENV PYTHONUNBUFFERED=1
ENV CRYPTOGRAPHY_DONT_BUILD_RUST=1
RUN apk add gcc musl-dev libc-dev libffi-dev postgresql-dev python3-dev bash --no-cache && pip install --upgrade pip
WORKDIR /app
COPY . /app/
RUN pip install -r /app/requirements.txt
