FROM kubamacek/fitkeeper:frontendimage1.0
RUN apt-get update && apt-get install -y --no-install-recommends chromium
ENV CHROME_BIN=chromium
WORKDIR /app
COPY . /app/
RUN npm install
RUN npm run test:ci
